# NumPy Notebook 3

In [1]:
import numpy as np
import pandas as pd

### 85. Print the data type of the numpy array below 

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

data_type = type(a)
print(data_type)

<class 'numpy.ndarray'>


### 86. Print the second element in the first row

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

element = a[0,1]
print(element)

2


### 87. Print the first column

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

column = a[:,0]
print(column)

[1 4]


### 88. Print the real part of the NumPy array

In [5]:
a = np.array([1+2j, 2+5j, 4+9j])

real = a.real
print(real)

[1. 2. 4.]


### 89. Print the imaginary part of the NumPy array

In [6]:
a = np.array([1+2j, 2+5j, 4+9j])

img = a.imag
print(img)

[2. 5. 9.]


### 90. Convert the data type from int to float

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

np_array = a.astype(float)
print(np_array)
print(np_array.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


### 91. Create a copy of the NumPy array

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = a.copy()
print(np_array)

[[1 2 3]
 [4 5 6]]


### 92. Print the diagonal of the NumPy array

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])

diag = a.diagonal()
print(diag)

[1 5]


### 93. Change the value of third element in 2nd row to 10

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a[1,2] = 10
print(a)

[[ 1  2  3]
 [ 4  5 10]]


### 94. Create a numpy array of ones with the same shape as the array 'a'. 

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = np.ones_like(a)
print(np_array)

[[1 1 1]
 [1 1 1]]


### 95. Create a numpy array of zeros with the same shape as the array 'a'. 

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = np.zeros_like(a)
print(np_array)

[[0 0 0]
 [0 0 0]]


### 96. Print the sum of the diagonal elements.

The sum of diagonal elements is also called its trace. 

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])

trace = np.trace(a)
print(trace)

6


### 97. Check whether all the elements of the array are finite or not 

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

check_finite = np.all(np.isfinite(a))
print(check_finite)

True


### 98. Check whether all the elements of the array are finite or not 

In [15]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

check_finite = np.all(np.isfinite(a))
print(check_finite)

False


### 99. Check whether the two numpy arrays are equal or not. 

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])

check_equal= np.array_equal(a,b)
print(check_equal)

True


### 100. Check whether the two numpy arrays are equal or not. 

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]], np.float32)

check_equal= np.array_equal(a,b)
print(check_equal)

True


### 101. Sum of array elements

In [18]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_sum = np.sum(a)
print(array_sum)

nan


### 102. Find the sum ignoring the nan elements

In [19]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_sum = np.nansum(a)
print(array_sum)

15.0


### 103. Find the product ignoring the nan elements

In [20]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_prod = np.nanprod(a)
print(array_prod)

120.0


### 104. Find the element-wise absolute value

In [21]:
a = np.array([[1, -2, 3], [4, -5, 6]])

np_array = np.abs(a)
print(np_array)

[[1 2 3]
 [4 5 6]]


### 105. Count the number of non-zero elements

In [22]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a)
print(count_non_zero)

5


### 106. Count the number of non-zero elements row-wise

In [23]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a, axis=0)
print(count_non_zero)

[1 2 2]


### 106. Count the number of non-zero elements column-wise

In [24]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a, axis=1)
print(count_non_zero)

[2 3]


### 107. Find the mean ignoring the nan elements

In [25]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_mean = np.nanmean(a)
print(array_mean)

3.0


### 108. Find the std dev ignoring the nan elements

In [26]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_std = np.nanstd(a)
print(array_std)

1.4142135623730951


### 109. Find the median ignoring the nan elements

In [27]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_median = np.nanmedian(a)
print(array_median)

3.0


### 110. Clip the array elements to a range

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])

min_range, max_range = (2, 5)
np_array = np.clip(a, min_range, max_range)
print(np_array)

[[2 2 3]
 [4 5 5]]
