# NumPy Notebook 2

## Mathematical Operations on NumPy Arrays

In [53]:
import numpy as np
import pandas as pd

### 36. Add two numpy arrays element-wise

In [54]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.add(a, b)
print(np_array)

[[2 3 6]
 [2 3 6]
 [3 4 8]]


### 37. Multiply two numpy arrays element-wise

In [55]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.multiply(a, b)
print(np_array)

[[ 1  2  9]
 [ 1  2  9]
 [ 2  3 16]]


### 38. Subtract two numpy arrays element-wise

In [56]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.subtract(a, b)
print(np_array)

[[ 0 -1  0]
 [ 0 -1  0]
 [-1 -2  0]]


### 39. Divide two numpy arrays element-wise

In [57]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.divide(a, b)
print(np_array)

[[1.         0.5        1.        ]
 [1.         0.5        1.        ]
 [0.5        0.33333333 1.        ]]


### 40-42. Trigonometric functions

sin(x)

In [58]:
a = np.array([1,2,3])

np_array = np.sin(a)
print(np_array)

[0.84147098 0.90929743 0.14112001]


cos(x)

In [59]:
a = np.array([1,2,3])

np_array = np.cos(a)
print(np_array)

[ 0.54030231 -0.41614684 -0.9899925 ]


tan(x)

In [60]:
a = np.array([1,2,3])

np_array = np.tan(a)
print(np_array)

[ 1.55740772 -2.18503986 -0.14254654]


### 43. Print the element-wise floor 

In [61]:
a = np.linspace(1, 2, 5)

np_array = np.floor(a)
print(np_array)

[1. 1. 1. 1. 2.]


### 44. Print the element-wise ceil

In [62]:
a = np.linspace(1, 2, 5)

np_array = np.ceil(a)
print(np_array)

[1. 2. 2. 2. 2.]


### 45. Print the element-wise nearest integer

In [63]:
a = np.linspace(1, 2, 5)

np_array = np.round(a)
print(np_array)

[1. 1. 2. 2. 2.]


### 46. Round to given number of decimal places

In [64]:
a = np.linspace(1, 2, 7)
decimal_places = 2

np_array = np.round(a, decimal_places)
print(np_array)

[1.   1.17 1.33 1.5  1.67 1.83 2.  ]


### 47. Calculate the element-wise exponential

In [65]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.exp(a)
print(np_array)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### 48. Calculate the element-wise exponential and round to two decimal places

In [66]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.round(np.exp(a), 2)
print(np_array)

[  2.72   7.39  20.09  54.6  148.41]


### 49. Calculate the element-wise natural logarithm 

In [67]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.log(a)
print(np_array)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


### 50. Calculate the element-wise natural logarithm and round to two decimal places

In [68]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.round(np.log(a), 2)
print(np_array)

[0.   0.69 1.1  1.39 1.61]


### 51. Calculate the element-wise logarithm at base 2

In [69]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])


np_array = np.log2(a)
print(np_array)

[0.         1.         1.5849625  2.         2.32192809]


### 52. Calculate the element-wise logarithm at base 2 and take floor of the result

In [70]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.floor(np.log2(a))
print(np_array)

[0. 1. 1. 2. 2.]


### 53. Find the sum of numpy array elements

In [71]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a)
print(sum_of_array)

10


### 54. Find the row-wise sum of numpy array elements

In [72]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a, axis=0)
print(sum_of_array)

[4 6]


### 55. Find the column-wise sum of numpy array elements

In [73]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a, axis=1)
print(sum_of_array)

[3 7]


### 56. Calculate the product of array elements

In [74]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a)
print(prod_of_array)

24


### 57. Find the row-wise product of numpy array elements

In [75]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a, axis=0)
print(prod_of_array)

[3 8]


### 58. Find the column-wise product of numpy array element

In [76]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a, axis=1)
print(prod_of_array)

[ 2 12]


### 59. Compute the square root of array elements

In [77]:
a = np.array([[1, 2], [3, 4]])

np_array = np.sqrt(a)
print(np_array)

[[1.         1.41421356]
 [1.73205081 2.        ]]


## Matrix and Vector Operations

### 60. Compute the dot product of two NumPy arrays 

In [78]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.dot(a, b)
print(np_array)

[[3 3]
 [7 7]]


### 61. Compute the row-wise dot product of two NumPy arrays 

In [79]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.einsum("ij,ij->i", a, b)
print(np_array)

[3 7]


### 62. Compute the matrix product of two NumPy arrays

In [80]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.matmul(a, b)
print(np_array)

[[3 3]
 [7 7]]


### 63. Compute the matrix product of two NumPy arrays using the @ operator

In [81]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = a @ b
print(np_array)

[[3 3]
 [7 7]]


### 64. Compute the length of the vector

In [82]:
a = np.arange(-4, 5)

vec_len = np.linalg.norm(a)
print(vec_len)

7.745966692414834


### 65. Sort the array inplace row-wise

In [83]:
a = np.array([[1,4],[3,1]])

np_array = np.sort(a, axis=0)
print(np_array)

[[1 1]
 [3 4]]


### 66. Sort the array inplace column-wise

In [84]:
a = np.array([[1,4],[3,1]])

np_array = np.sort(a, axis=1)
print(np_array)

[[1 4]
 [1 3]]


### 67. Sort the flattened array

In [85]:
a = np.array([[1,4],[3,1]])

np_array = np.sort(a, axis=None)
print(np_array)

[1 1 3 4]


### 68. Order of Indices in a Sorted NumPy Array

In [86]:
a = np.array([3, 1, 2])

np_array = np.argsort(a)
print(np_array)

[1 2 0]


### 69-71. Find the index corresponding to the Maximum Values.

In [87]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

#### In a flattened array

In [88]:
max_index = np.argmax(a)
print(max_index)

6


#### Indices of max along column

In [89]:
max_index = np.argmax(a, axis=1)
print(max_index)

[4 1]


#### Indices of max along row

In [90]:
max_index = np.argmax(a, axis=0)
print(max_index)

[0 1 1 1 0]


### 72-74. Find the index corresponding to the Minimum Values.

In [91]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

#### In a flattened array

In [92]:
min_index = np.argmin(a)
print(min_index)

3


#### Indices of min along column

In [93]:
min_index = np.argmin(a, axis=1)
print(min_index)

[3 4]


#### Indices of min along row

In [94]:
min_index = np.argmin(a, axis=0)
print(min_index)

[1 0 0 0 1]


### 75. Print the indices of non-zero elements

In [95]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])

non_zero_ind = np.nonzero(a)
print(non_zero_ind)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))


### 76. Find the mean of the whole numpy array

In [96]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a)
print(mean)

2.5


### 77. Find the mean of the numpy array along row-axis

In [97]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a, axis=0)
print(mean)

[2. 3.]


### 78. Find the mean of the numpy array along column-axis

In [98]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a, axis=1)
print(mean)

[1.5 3.5]


### 79. Find the median of the whole numpy array

In [99]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a)
print(median)

2.5


### 80. Find the median of the numpy array along row-axis

In [100]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a, axis=0)
print(median)

[2. 3.]


### 81. Find the median of the numpy array along column-axis

In [101]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a, axis=1)
print(median)

[1.5 3.5]


### 82. Find the std dev of the whole numpy array

In [102]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a)
print(std_dev)

1.118033988749895


### 83. Find the std dev of the numpy array along row-axis

In [103]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a, axis=0)
print(std_dev)

[1. 1.]


### 84. Find the std dev of the numpy array along column-axis

In [104]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a, axis=1)
print(std_dev)

[0.5 0.5]
