# NumPy Notebook 1

In [1]:
import pandas as pd
import numpy as np

## Create a Numpy Array

### 1. Create a NumPy array from a python list

In [3]:
a = [1, 2, 3]

np_array = np.array(a)
print(np_array)

[1 2 3]


### 2. Print the type of the array created above

In [4]:
type(np_array)

numpy.ndarray

### 3. Create a NumPy array from a python list of lists

In [5]:
a = [[1,2,3], [4,5,6]]

np_array = np.array(a)
print(np_array)

[[1 2 3]
 [4 5 6]]


### 4. Print the type of the array created above

In [6]:
type(np_array)

numpy.ndarray

### 5. While creating the numpy array, specify the data type as float32.

In [10]:
a = [[1,2,3], [4,5,6]]

np_array = np.array(a, dtype='float32')
print(np_array)

[[1. 2. 3.]
 [4. 5. 6.]]


### 6. Create a NumPy array of Zeros

In [11]:
np_array = np.zeros(3)
print(np_array)

[0. 0. 0.]


### 7. Create a multi-dimensional NumPy array of Zeros

In [13]:
np_array = np.zeros((3,3))
print(np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 8. Create a NumPy array of Ones

In [14]:
np_array = np.ones(4)
print(np_array)

[1. 1. 1. 1.]


### 9. Create a multi-dimensional NumPy array of Ones

In [15]:
np_array = np.ones((3,2))
print(np_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### 10. Create an Identity Numpy Array of order 3

In [16]:
np_array = np.identity(3)
print(np_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 11-13. Create an equally spaced Numpy Array with a specific step

Generate values from start=0 to stop=10 with step=1:

In [18]:
np_array = np.arange(0,10,1)
print(np_array)

[0 1 2 3 4 5 6 7 8 9]


Generate values from start=5 to stop=11 with step=1:

In [20]:
np_array = np.arange(5,11,1)
print(np_array)

[ 5  6  7  8  9 10]


Generate values start=5 to step=11 with step=2.

In [21]:
np_array = np.arange(5,11,2)
print(np_array)

[5 7 9]


### 14-15. Create an equally spaced Numpy Array with a specific array size

Generate a numpy array of size 5 with start=0 to stop=10

In [22]:
np_array = np.linspace(0,10,5)
print(np_array)

[ 0.   2.5  5.   7.5 10. ]


Generate a numpy array of size 5 with start=5 to stop=7

In [23]:
np_array = np.linspace(5,7,5)
print(np_array)

[5.  5.5 6.  6.5 7. ]


### 16-17. Generate a random numpy array 

Generate a random integer array of size 5 with start=0 to stop=10

In [27]:
np_array = np.random.randint(0,10,size=5)
print(np_array)

[4 2 5 7 6]


Generate a random float array of size 10

In [28]:
np_array = np.random.rand(10)
print(np_array)

[0.03215077 0.89632243 0.79965766 0.23677397 0.25189185 0.31665094
 0.40702355 0.78737043 0.29628773 0.07646977]


### 18-19. Generate NumPy Array from a Pandas Series using two methods

### Method 1:

In [29]:
s = pd.Series([1,2,3,4], name = "col")

np_array = np.array(s)
print(np_array)

[1 2 3 4]


### Method 2:

In [30]:
s = pd.Series([1,2,3,4], name = "col")

np_array = s.to_numpy()
print(np_array)

[1 2 3 4]


## NumPy Array Manipulation Methods

### 20-21. Shape of the NumPy Array in two ways

### Method 1:

In [35]:
a = np.ones((2, 3))

shape_of_a = a.shape
print(shape_of_a)

(2, 3)


### Method 2:

In [37]:
a = np.ones((2, 3))

shape_of_a = np.shape(a)
print(shape_of_a)

(2, 3)


### 22. Reshape the NumPy Array to 2*5

In [39]:
a = np.arange(10)

np_array = a.reshape(2,5)
print(np_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 23-24. Transpose the NumPy Array in two ways

Method 1:

In [42]:
a = np.array([[1,2,3], [4,5,6]])

np_array = a.T
print(np_array)

[[1 4]
 [2 5]
 [3 6]]


### Method 2:

In [44]:
a = np.array([[1,2,3], [4,5,6]])

np_array = np.transpose(a)
print(np_array)

[[1 4]
 [2 5]
 [3 6]]


### 25-27. Concatenate multiple NumPy arrays to form one NumPy Array

### Concatenate row-wise

In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np_array = np.concatenate((a,b), axis=0)
print(np_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Concatenate column-wise

In [50]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np_array = np.concatenate((a,b), axis=1)
print(np_array)

[[1 2 5 6]
 [3 4 7 8]]


### Concatenate to generate a flat NumPy Array

In [56]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.concatenate((a.flatten(), b.flatten()))
print(np_array)

[1 2 3 4 5 6]


### 28-29. Concatenate using vstack() and hstack()

vstack()

In [60]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.vstack((a,b))
print(np_array)

[[1 2]
 [3 4]
 [5 6]]


hstack()

In [63]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np_array = np.hstack((a,b))
print(np_array)

[[1 2 5 6]
 [3 4 7 8]]


### 30. Flatten NumPy Array

In [64]:
a = np.array([[1,2], [3,4]])

np_array = a.flatten()
print(np_array)

[1 2 3 4]


### 31-33. Print Unique Elements of a NumPy Array

In [66]:
a = np.array([[1,2], [3,2]])

np_array = np.unique(a)
print(np_array)

[1 2 3]


return unique rows

In [68]:
a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.unique(a, axis=0)
print(np_array)

[[1 2 3]
 [2 3 4]]


return unique columns

In [70]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

np_array = np.unique(a, axis=1)
print(np_array)

[[1 3]
 [1 3]
 [1 4]]


### 34. Squeeze the NumPy Array

In [72]:
a = np.array([[[0], [1], [2]]])

np_array = np.squeeze(a)
print(np_array)

[0 1 2]


### 35. Get Python list from NumPy array

In [76]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

py_list = a.tolist()
print(py_list)

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]
