# NumPy Notebook 4

In [88]:
import numpy as np

### 111. Generate 10 random numbers from a uniform distribution between 0 and 1.

In [89]:
np.random.rand(10)

array([0.68384312, 0.20587172, 0.6164337 , 0.92447161, 0.07962825,
       0.48539683, 0.69856363, 0.08156848, 0.86910236, 0.43310568])

### 112. Create an array of 5 random integers between 50 and 100.

In [90]:
np.random.randint(50, 101, size=5)

array([66, 98, 96, 74, 65])

### 113. Generate 15 random numbers from a standard normal distribution (mean=0, std=1).

In [91]:
np.random.randn(15)

array([-0.4981647 ,  2.0763131 , -1.92853502,  1.64785998, -1.00448234,
       -0.90135582,  0.893222  ,  0.51187765, -0.8690435 ,  2.39840183,
       -1.00139033,  1.60247324,  1.498786  ,  0.52521122,  0.83108041])

### 114. Create a 4x4 matrix with random values between -1 and 1.

In [92]:
np.random.uniform(-1, 1, size=(4,4))

array([[-0.3920718 , -0.01399453,  0.95872068, -0.35298346],
       [-0.62086565, -0.38954178, -0.31177615,  0.35906058],
       [-0.89237001,  0.61320752,  0.20590038,  0.31042637],
       [ 0.49531958,  0.07125235, -0.78168704, -0.00760743]])

### 115. Generate a random float between 0 and 10.

In [93]:
np.random.uniform(0, 10)

1.7234262762093788

### 116. Generate 20 random numbers from a normal distribution (mean=5, std=2).

In [94]:
np.random.normal(5, 2, size=20)

array([5.04473549, 5.63580659, 8.92223689, 2.026502  , 7.01428212,
       7.6688689 , 4.92922832, 3.88620774, 4.86950588, 3.49738417,
       1.69188702, 2.0425492 , 2.64407903, 5.24532979, 7.71871383,
       2.99068633, 5.28254303, 4.34293873, 7.8587662 , 0.28039953])

### 117. Create an array of 12 random integers from a Poisson distribution (mean=4).

In [95]:
np.random.poisson(4, size=12)

array([3, 8, 3, 6, 5, 8, 7, 3, 3, 4, 5, 2])

### 118. Generate a 3x3 array of random numbers from an exponential distribution (scale=2).

In [96]:
np.random.exponential(scale=2, size=(3,3))

array([[1.80993813e-03, 4.40003184e+00, 8.29205877e-01],
       [1.99293212e+00, 8.03065344e-01, 4.39626527e+00],
       [2.61365360e+00, 1.98140183e-01, 2.45312684e+00]])

### 119. Create 100 random numbers from a binomial distribution (n=10, p=0.3).

In [97]:
np.random.binomial(10, 0.3, size=100)

array([5, 3, 6, 3, 1, 3, 3, 3, 4, 2, 5, 3, 3, 3, 1, 3, 3, 2, 5, 3, 2, 3,
       3, 4, 4, 3, 3, 4, 4, 3, 4, 2, 3, 3, 1, 4, 4, 3, 3, 1, 3, 3, 3, 4,
       1, 6, 1, 1, 3, 3, 2, 3, 5, 4, 1, 2, 3, 3, 3, 2, 3, 3, 1, 1, 1, 3,
       3, 1, 2, 4, 4, 1, 4, 2, 6, 2, 2, 3, 3, 1, 3, 4, 3, 3, 4, 3, 3, 4,
       4, 2, 4, 3, 5, 2, 2, 3, 5, 1, 4, 4])

### 120. Generate a random number from a geometric distribution (p=0.2).

In [98]:
np.random.geometric(0.2)

10

### 121. Create a 1D array of integers from 1 to 10 and shuffle them randomly.

In [99]:
array = np.arange(1, 11)
np.random.shuffle(array)
print(array)

[ 3  1  5  4  2  6  9 10  8  7]


### 122. Choose 5 random elements from a list without replacement.

In [100]:
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
np.random.choice(list1, size=5, replace=False)

array([40, 60, 90, 80, 30])

### 123. Select 7 random integers between 1 and 100 with replacement.

In [101]:
r = np.arange(1, 101)
np.random.choice(r, size=7, replace=True)

array([ 6, 94, 84, 73, 82,  3, 36])

### 124. Shuffle the rows of a 3x3 matrix randomly.

In [102]:
matrix = np.arange(1, 10).reshape(3,3)
np.random.shuffle(matrix)
print(matrix)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


### 125. Choose 4 random elements from [1, 2, 3, 4, 5, 6, 7, 8] with specific probabilities.

In [103]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
np.random.choice(list1, size=4, p=[0.1, 0.2, 0.1, 0.15, 0.1, 0.1, 0.1, 0.15])

array([5, 7, 2, 3])

### 126. Set a random seed of 42 and generate a 5x5 matrix of random values.

In [104]:
np.random.seed(42)
result1 = np.random.rand(5, 5)
print(result1)
print()

# repeating to verify
np.random.seed(42)
result2 = np.random.rand(5, 5)
print(result2)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]


### 127. Set a random seed, generate 10 random numbers, and reset the seed to generate the same numbers again.

In [105]:
np.random.seed(123)
result1 = np.random.rand(10)
print(result1)
print()

# reset seed
np.random.seed(123)
result2 = np.random.rand(10)
print(result2)


[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


### 128. Create a 5x5 matrix of random integers between 1 and 50 and replace values > 25 with -1.

In [106]:
matrix = np.random.randint(1, 51, size=(5,5))
matrix[matrix > 25] = -1
print(matrix)

[[-1 -1 -1 -1 20]
 [15 -1 -1 17  5]
 [-1  4  3 21 -1]
 [ 3 21 -1 -1  8]
 [-1 -1 -1 -1 -1]]


### 129. Generate a 1D array of 10 random integers (1 to 20) and find the index of the largest number.

In [107]:
array = np.random.randint(1, 21, size=10)
index = np.argmax(array)
print(array)
print("Index of largest number:", index)

[ 3  2 13  9  4 11  6  1 12  3]
Index of largest number: 2


### 130. Generate a 1D array of 10 random integers (1 to 100). Sort the array in ascending order and retrieve the sorted indices. Then use these indices to display the sorted array.

In [108]:
array = np.random.randint(1, 101, size=10)
sorted_indices = np.argsort(array)
sorted_array = array[sorted_indices]
print(array)
print("Sorted indices:", sorted_indices)
print("Sorted array:", sorted_array)

[59 11 23 78 19 16 28 31 53 71]
Sorted indices: [1 5 4 2 6 7 8 0 9 3]
Sorted array: [11 16 19 23 28 31 53 59 71 78]
